---
# Setup a basic Foreman/Puppet Environment using libvirt vagrant boxes
# Recommended RAM >= 16GB

- hosts: localhost
  vars:
    ### working directory setting
    # set this to where you have your modules (in the form of st_<name>, not saskte-st_<name>
    puppet_module_path: "{{ ansible_env.HOME }}/proj/puppet"
    # set this to where foreman is expecting modules:
    # this works for puppet 3
    foreman_module_path: /etc/puppet/modules
    # this works for puppet 4
    # foreman_module_path: /etc/puppetlabs/code/environments/development/modules'
    # 
    ### Versions and path variants
    foreman_version: 1.12
    # if version is 1.12 or less then use this:
    autosign_path: /etc/puppet
    # if version is 1.13 or higher:
    # autosign_path: /etc/puppetlabs/puppet
    # 
    ### agent control 
    # change to true if you want that agent to run
    # NB, running all three means you should have 16GB RAM
    launch_centos_5_box: false
    launch_centos_6_box: true
    launch_centos_7_box: false

  tasks:
    - name: verify work dir exists
      stat:
        path: "{{ puppet_module_path }}"
      register: puppet_module_path_result

    - include: dependency_setup.yaml
      static: no
      when: puppet_module_path_result.stat.exists

    - include: vagrant_setup.yaml
      static: no
      when: puppet_module_path_result.stat.exists




